if [[ $OSTYPE == darwin* ]]
then
  SED_EXTRA_ARGS='""';
fi

sed -i $SED_EXTRA_ARGS "s?{{CLIENT_ID}}?${CLIENT_ID}?g" $KUBERNETES_MANIFEST_FILE_PATH;
sed -i $SED_EXTRA_ARGS "s?{{CLIENT_SECRET}}?${CLIENT_SECRET}?g" $KUBERNETES_MANIFEST_FILE_PATH;
sed -i $SED_EXTRA_ARGS "s?{{TOKEN_URL}}?${TOKEN_URL}?g" $KUBERNETES_MANIFEST_FILE_PATH;
sed -i $SED_EXTRA_ARGS "s?{{BASE_URI}}?${BASE_URI}?g" $KUBERNETES_MANIFEST_FILE_PATH;
sed -i $SED_EXTRA_ARGS "s?{{REFRESH_TOKEN}?${REFRESH_TOKEN}?g" $KUBERNETES_MANIFEST_FILE_PATH;
