name: Connector Deployment

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true 
    - run: gem install workato-connector-sdk
    - name: Relase changes to workato.
      env:
        WORKATO_EMAIL: ${{ secrets.WORKATO_EMAIL }}
        WORKATO_TOKEN: ${{ secrets.WORKATO_TOKEN }}
      run: workato push --connector=travelperk-connector/connector.rb --logo=travelperk-connector/travelperk.png --notes='release'
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE:  Status - ${{ job.status }}
        SLACK_TITLE: Release workato connector
        SLACK_ICON_EMOJI: ":pepeok:"
        SLACK_USERNAME: Workato Connector
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_FOOTER: ''
