name: Connector Deployment

on: 
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: workato
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true 
    - run: gem install workato-connector-sdk
    - name: Get changed files travelperk-connector.
      id: changed-files-specific
      uses: tj-actions/changed-files@v29
      with:
        files: |
          travelperk-connector/connector.rb
    - name: Release changes to workato if anything is changed in travelperk-connector.
      env:
        WORKATO_API_EMAIL: ${{ secrets.WORKATO_API_EMAIL }}
        WORKATO_API_TOKEN: ${{ secrets.WORKATO_API_TOKEN }}
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run:
        workato push --connector=travelperk-connector/connector.rb --logo=travelperk-connector/travelperk.png --notes='${{ github.event.head_commit.message }}'
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE:  Status - ${{ job.status }}
        SLACK_TITLE: Release workato connector
        SLACK_ICON_EMOJI: ":pepeok:"
        SLACK_USERNAME: Workato Connector
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_FOOTER: ''
