name: Connector Deployment

on: 
  push:
    branches: [ master, init ]

jobs:
  release:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.4.10', '2.5', '2.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true 
    - name: Push to DEV workspace.
      env: # Only needed if using encrypted files.
        WORKATO_API_EMAIL: ${{ secrets.WORKATO_EMAIL}}
        WORKATO_API_TOKEN: ${{ secrets.WORKATO_TOKEN}}
      run: workato push --connector=travelperk-connector/connector.rb
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE:  Status - ${{ job.status }}
        SLACK_TITLE: Release workato connector
        SLACK_ICON_EMOJI: ":pepeok:"
        SLACK_USERNAME: Workato Connector
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_FOOTER: ''
