name: Connector Unit Test & Deployment

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    

jobs:
  test:
    runs-on: ubuntu-latest
    environment: workato

    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true 
 
    - run: gem install workato-connector-sdk
    
    - name: Run tests
      run: |
        cd fyle-sdk
      env: # Only needed if using encrypted files.
        WORKATO_API_EMAIL: ${{ secrets.WORKATO_API_EMAIL }}
        WORKATO_API_TOKEN: ${{ secrets.WORKATO_API_TOKEN }}      
      
      run: bundle exec rspec
