name: Connector Unit Test & Deployment

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    

jobs:
  test:
    runs-on: ubuntu-latest
    environment: workato

    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true 
 
    - run: gem install workato-connector-sdk

    - name: Run tests
      env: # Only needed if using encrypted files.
        WORKATO_API_EMAIL: ${{ secrets.WORKATO_API_EMAIL }}
        WORKATO_API_TOKEN: ${{ secrets.WORKATO_API_TOKEN }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TOKEN_URL: ${{ secrets.TOKEN_URL }}
        BASE_URI: ${{ secrets.BASE_URI }}
        REFRESH_TOKEN: $ {{ secrets.REFRESH_TOKEN }}
      run: |
        cd fyle-sdk
        bash run.sh
        bundle install
        bundle exec rspec
